### PR TITLE
Check all variants build correctly

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by chrisstaite** [comment]
Does the script bit not need changing to take the different boards?

**Comment by peternewman** [comment]
Good thing someone is paying attention! I get the feeling you might have known this was the case, as it's currently failing to build on the Teensy 2.0's. I'm guessing that's expected?

Turns out we can also do builds for multiple boards at once. Pros are fewer builds overall, cons are you can't easily see from Travis which board it's failed for.
http://docs.platformio.org/en/latest/ci/travis.html#integration
e.g.
https://travis-ci.org/felis/USB_Host_Shield_2.0/jobs/278452084

**Comment by chrisstaite** [comment]
For the number of commits we get I don't think we need worry about faster builds...  Nice find though.  Yeah, the Teensy 2.0 is a different architecture, so it's got a separate library to do this stuff, although it's not as fully featured now you've done this much extra work.

**Comment by peternewman** [comment]
Which library is/was that then? I've set the Teensy 2.0 builds to be expected failures until/if someone chooses to spend some time trying to fix them. Do you think they would just work if the basic issues were resolved, or would timing etc all be wrong too?

**Comment by chrisstaite** [comment]
The Teensy 2.0 boards are Atmel AVR based, whereas the 3.0+ boards are Cortex M-series ARM based.  They have totally different hardware and clocks.  All of the standard Arduino DMX libraries function on the Teensy 2.0 boards.

**Comment by peternewman** [comment]
Gotcha, okay I've stopped it trying to build the Teensy 2 versions. I'd done similar levels of work on https://github.com/mathertel/DmxSerial2 , but I think that had basically hit the limits of the controller's CPU etc. I think the Teensy stuff should be able to go a lot further though, as you'll probably see soon...

**Pull request merged**
